# kustomize/base/services/config-service-rental-estate/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: microservice
    repo: ../../../../charts/microservice
    releaseName: config-service
    valuesInline:
      service:
        port: 8888
