# kustomize/base/services/user-management-estate-rental-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: microservice
    repo: ../../../../charts/microservice
    releaseName: user-management-service
    valuesInline:
      service:
        port: 8081
