apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Définition globale du dossier contenant tes charts locaux
helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: microservice
    releaseName: config-service
    valuesFile: values-dev.yaml
