replicaCount: 1

image:
  repository: authorization-service
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: CONFIG_SERVER_URL
    value: "http://config-service-microservice:8888"
  - name: USER_MANAGEMENT_SERVICE_URL
    value: "http://user-management-service-microservice:8081"
  - name: JWT_ISSUER
    value: "http://authorization-service-microservice:9000"
  - name: user.uri
    value: "http://user-management-service-microservice:8081"
  - name: app.metamask.signature-message-prefix
    value: "Sign this message to authenticate: "
  - name: SPRING_SECURITY_OAUTH2_AUTHORIZATIONSERVER_ISSUER
    value: http://authorization-service-microservice:9000