# Example values for stag - can be customized further
replicaCount: 2

image:
  repository: auth-service
  tag: 1.0.0

service:
  type: ClusterIP
  port: 9000

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "stag"

configMapData:
  CONFIG_SERVER_URL: "http://config-service-stag:8888"
  USER_MANAGEMENT_SERVICE_URL: "http://user-management-service-stag:8081"
  JWT_ISSUER: "http://auth-server-stag:9000"
