# kustomize/base/services/gateway-estate-rental-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: microservice
    repo: ../../../../charts/microservice
    releaseName: gateway-service
    valuesInline:
      service:
        port: 8880
        type: LoadBalancer # Gateway might need LoadBalancer
