# gateway-service values for dev

replicaCount: 1

image:
  repository: gateway-service
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8880

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: CONFIG_SERVER_URL
    value: "http://config-service:8888"
  - name: FRONTEND_URL
    value: "http://frontend:3000"
  - name: AUTH_SERVER_URL
    value: "http://auth-server:9000"
  - name: USER_MANAGEMENT_SERVICE_URL
    value: "http://user-management-service:8081"
  - name: RENTAL_AGREEMENT_URL
    value: "http://rental-agreement-service:8082"
  - name: PROPERTY_MICROSERVICE_URL
    value: "http://property-service:8083"
  - name: NOTIFICATION_MICROSERVICE_URL
    value: "http://notification-service:8084"
  - name: OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: gateway-secrets
        key: OAUTH_CLIENT_ID
  - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: gateway-secrets
        key: OAUTH_CLIENT_SECRET
