apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services/gateway-estate-rental-service
  - services/frontend
  - services/config-service
  - services/authorization-service
  - services/user-management-service
  - networking
