apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services/authorization-service
  - services/config-service-rental-estate
  - services/gateway-estate-rental-service
  - services/user-management-estate-rental-service
